---
title: "Dashboard of MoD simulation"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

<style type="text/css">

.chart-title {  /* chart_title  */
   font-size: 20px;
   font-family: Arial;

</style>


```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(dplyr)
library(scales)
library(latex2exp)
library(viridis)
library(RColorBrewer)

# display.brewer.all()
#display.brewer.pal(n = 11, name = 'RdYlBu')
# display.brewer.pal(n = 11, name = 'Paired')
# col_idle <-brewer.pal(n = 11, name = "Paired")[4]
# col_assign <-brewer.pal(n = 11, name = "Paired")[2]
# col_oprt <-brewer.pal(n = 11, name = "Paired")[11]
# col_inter <-brewer.pal(n = 11, name = "Paired")[8]
# col_intra <-brewer.pal(n = 11, name = "Paired")[10]


col_idle <- viridis(4)[2]
col_assign <-"#ff7f0e"
col_oprt <-viridis(4)[4]
col_inter <-viridis(4)[3]
col_intra <-viridis(4)[1]

# col_intra <-"#d62728"



# Load dataset
load("C:/Users/User/Documents/research/taxi-relocation/dashboard/vis_dat_default.RData")
load("C:/Users/User/Documents/research/taxi-relocation/dashboard/vis_dat_inter_relo.RData")
load("C:/Users/User/Documents/research/taxi-relocation/dashboard/vis_dat_intra_s1.RData")
load("C:/Users/User/Documents/research/taxi-relocation/dashboard/vis_dat_intra_s2.RData")


```



Without-relocation vs Inter-relocation
=======================================================================

Column {data-width=200}
-----------------------------------------------------------------------

### Without Relocation

```{r}
pl <- vis_dat_default %>% filter(time==1) %>%
  plot_ly(
    x = ~X, 
    y = ~Y, 
    # size = ~pop, 
    # color = ~state, 
    # frame = ~time, 
    text = ~paste('</br> VehicleID: ', VehicleID,
                      '</br> State: ', state), 
    hoverinfo = "text"
  ) %>%
  add_markers(color = ~factor(state),
              colors = c(col_assign,col_idle,col_oprt),
              frame = ~time) %>%
  animation_opts(frame=1,transition = 0, easing = "linear", redraw = FALSE) %>%
  layout(legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5),
         autosize = F, width = 600, height = 600,
         xaxis = list(title = "",
                      ticktext = list(0,1,2,3,4,5,6,7), 
                      tickvals = list(0,1000,2000,3000,4000,5000,6000,7000),
                      tickmode = "array",
                      mirror = "ticks",
                      range = c(0, 7000),
                      gridcolor = "grey80",
                      showline = TRUE),
         yaxis = list(title = "",
                      ticktext = list(0,1,2,3,4,5,6), 
                      tickvals = list(0,1000,2000,3000,4000,5000,6000),
                      tickmode = "array",
                      mirror = "ticks",
                      range = c(0, 6000),
                      gridcolor = "grey80",
                      showline = TRUE))

pl
```

Column {data-width=200}
-----------------------------------------------------------------------

### With Inter-zonal Relocation

```{r}
pl2 <- vis_dat_inter_relo %>% filter(time==1) %>%
  plot_ly(
    x = ~X, 
    y = ~Y, 
    # size = ~pop, 
    # color = ~state, 
    # frame = ~time, 
    text = ~paste('</br> VehicleID: ', VehicleID,
                      '</br> State: ', state), 
    hoverinfo = "text"
  ) %>%
  add_markers(color = ~factor(state),
              colors = c(col_assign,col_idle,col_inter,col_oprt),
              frame = ~time) %>%
  animation_opts(frame=1,transition = 0, easing = "linear", redraw = FALSE) %>%
  layout(legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5),
         autosize = F, width = 600, height = 600,
         xaxis = list(title = "",
                      ticktext = list(0,1,2,3,4,5,6,7), 
                      tickvals = list(0,1000,2000,3000,4000,5000,6000,7000),
                      tickmode = "array",
                      mirror = "ticks",
                      range = c(0, 7000),
                      gridcolor = "grey80",
                      showline = TRUE),
         yaxis = list(title = "",
                      ticktext = list(0,1,2,3,4,5,6), 
                      tickvals = list(0,1000,2000,3000,4000,5000,6000),
                      tickmode = "array",
                      mirror = "ticks",
                      range = c(0, 6000),
                      gridcolor = "grey80",
                      showline = TRUE))

pl2
```

Column {data-width=200}
-----------------------------------------------------------------------

### Without Relocation

```{r}
pl3 <- vis_dat_intra_s1 %>% filter(time==1) %>%
  plot_ly(
    x = ~X, 
    y = ~Y, 
    # size = ~pop, 
    # color = ~state, 
    # frame = ~time, 
    text = ~paste('</br> VehicleID: ', VehicleID,
                      '</br> State: ', state), 
    hoverinfo = "text"
  ) %>%
  add_markers(color = ~factor(state),
              colors = c(col_assign,col_idle,col_inter,col_intra,col_oprt),
              frame = ~time) %>%
  animation_opts(frame=1,transition = 0, easing = "linear", redraw = FALSE) %>%
  layout(legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5),
         autosize = F, width = 600, height = 600,
         xaxis = list(title = "",
                      ticktext = list(0,1,2,3,4,5,6,7), 
                      tickvals = list(0,1000,2000,3000,4000,5000,6000,7000),
                      tickmode = "array",
                      mirror = "ticks",
                      range = c(0, 7000),
                      gridcolor = "grey80",
                      showline = TRUE),
         yaxis = list(title = "",
                      ticktext = list(0,1,2,3,4,5,6), 
                      tickvals = list(0,1000,2000,3000,4000,5000,6000),
                      tickmode = "array",
                      mirror = "ticks",
                      range = c(0, 6000),
                      gridcolor = "grey80",
                      showline = TRUE))

pl3
```
